Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\ProgramData\Miniconda3\envs\mem680\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\Miniconda3\envs\mem680\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Miniconda3\envs\mem680\lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "C:\ProgramData\Miniconda3\envs\mem680\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\ProgramData\Miniconda3\envs\mem680\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Miniconda3\envs\mem680\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Miniconda3\envs\mem680\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------


# This is a dataGet Command
dget_resp = df_api.dataGet("d/49965349", os.path.abspath(datapath), wait=True)
dget_resp

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mException[0m                                 Traceback (most recent call last)
Cell [1;32mIn[7], line 2[0m
[0;32m      1[0m [38;5;66;03m# This is a dataGet Command[39;00m
[1;32m----> 2[0m dget_resp [38;5;241m=[39m [43mdf_api[49m[38;5;241;43m.[39;49m[43mdataGet[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43md/49965349[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mos[49m[38;5;241;43m.[39;49m[43mpath[49m[38;5;241;43m.[39;49m[43mabspath[49m[43m([49m[43mdatapath[49m[43m)[49m[43m,[49m[43m [49m[43mwait[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[0;32m      3[0m dget_resp

File [1;32mC:\ProgramData\Miniconda3\envs\mem680\lib\site-packages\datafed\CommandLib.py:747[0m, in [0;36mAPI.dataGet[1;34m(self, item_id, path, encrypt, orig_fname, wait, timeout_sec, context)[0m
[0;32m    744[0m [38;5;28;01mfor[39;00m ids [38;5;129;01min[39;00m item_id:
[0;32m    745[0m     msg[38;5;241m.[39mid[38;5;241m.[39mappend([38;5;28mself[39m[38;5;241m.[39m_resolve_id(ids, context))
[1;32m--> 747[0m reply [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_mapi[49m[38;5;241;43m.[39;49m[43msendRecv[49m[43m([49m[43mmsg[49m[43m)[49m
[0;32m    749[0m [38;5;66;03m# May initiate multiple transfers - one per repo with multiple records per transfer[39;00m
[0;32m    750[0m [38;5;66;03m# Downloads may be Globus OR HTTP, but not both[39;00m
[0;32m    752[0m glob_ids [38;5;241m=[39m []

File [1;32mC:\ProgramData\Miniconda3\envs\mem680\lib\site-packages\datafed\MessageLib.py:354[0m, in [0;36mAPI.sendRecv[1;34m(self, msg, timeout, nack_except)[0m
[0;32m    352[0m [38;5;28mself[39m[38;5;241m.[39msend(msg)
[0;32m    353[0m _timeout [38;5;241m=[39m timeout [38;5;28;01mif[39;00m timeout [38;5;241m!=[39m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39m_timeout
[1;32m--> 354[0m reply, mt, ctxt [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mrecv[49m[43m([49m[43m_timeout[49m[43m,[49m[43m [49m[43mnack_except[49m[43m)[49m
[0;32m    355[0m [38;5;28;01mif[39;00m reply [38;5;241m==[39m [38;5;28;01mNone[39;00m:
[0;32m    356[0m     [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124m"[39m[38;5;124mTimeout!!!!!!!!![39m[38;5;124m"[39m)

File [1;32mC:\ProgramData\Miniconda3\envs\mem680\lib\site-packages\datafed\MessageLib.py:399[0m, in [0;36mAPI.recv[1;34m(self, timeout, nack_except)[0m
[0;32m    397[0m [38;5;28;01mif[39;00m msg_type [38;5;241m==[39m [38;5;124m"[39m[38;5;124mNackReply[39m[38;5;124m"[39m [38;5;129;01mand[39;00m _nack_except:
[0;32m    398[0m     [38;5;28;01mif[39;00m reply[38;5;241m.[39merr_msg:
[1;32m--> 399[0m         [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m(reply[38;5;241m.[39merr_msg)
[0;32m    400[0m     [38;5;28;01melse[39;00m:
[0;32m    401[0m         [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124m"[39m[38;5;124mServer error [39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(reply[38;5;241m.[39merr_code))

[1;31mException[0m: Authentication required
=======
  File "C:\Conda\envs\mem680\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "C:\Conda\envs\mem680\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
if not df_api.endpointDefaultGet():
    print("Please follow instructions in the link below to find your Globus Endpoint:")
    print(
        "https://ornl.github.io/DataFed/system/getting_started.html#install-identify-globus-endpoint"
    )
    endpoint = input(
        "\nPlease enter either the Endpoint UUID or Legacy Name for your Globus Endpoint: "
    )
    df_api.endpointDefaultSet(endpoint)

print("Your default Globus Endpoint in DataFed is:\n" + df_api.endpointDefaultGet())
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [1;32mIn [6], line 6[0m
[0;32m      2[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mPlease follow instructions in the link below to find your Globus Endpoint:[39m[38;5;124m"[39m)
[0;32m      3[0m     [38;5;28mprint[39m(
[0;32m      4[0m         [38;5;124m"[39m[38;5;124mhttps://ornl.github.io/DataFed/system/getting_started.html#install-identify-globus-endpoint[39m[38;5;124m"[39m
[0;32m      5[0m     )
[1;32m----> 6[0m     endpoint [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m
[0;32m      7[0m [43m        [49m[38;5;124;43m"[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mPlease enter either the Endpoint UUID or Legacy Name for your Globus Endpoint: [39;49m[38;5;124;43m"[39;49m
[0;32m      8[0m [43m    [49m[43m)[49m
[0;32m      9[0m     df_api[38;5;241m.[39mendpointDefaultSet(endpoint)
[0;32m     11[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mYour default Globus Endpoint in DataFed is:[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m [38;5;241m+[39m df_api[38;5;241m.[39mendpointDefaultGet())

File [1;32m~\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelbase.py:1174[0m, in [0;36mKernel.raw_input[1;34m(self, prompt)[0m
[0;32m   1167[0m [38;5;124;03m"""Forward raw_input to frontends[39;00m
[0;32m   1168[0m 
[0;32m   1169[0m [38;5;124;03mRaises[39;00m
[0;32m   1170[0m [38;5;124;03m------[39;00m
[0;32m   1171[0m [38;5;124;03mStdinNotImplementedError if active frontend doesn't support stdin.[39;00m
[0;32m   1172[0m [38;5;124;03m"""[39;00m
[0;32m   1173[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m-> 1174[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(
[0;32m   1175[0m         [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m   1176[0m     )
[0;32m   1177[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[0;32m   1178[0m     [38;5;28mstr[39m(prompt),
[0;32m   1179[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[0;32m   1180[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[0;32m   1181[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m   1182[0m )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.
>>>>>>> 6705a020b0958f423ff6ce78f503bc970904e6d0

